#include <sstream>
#include <fstream>
#include <iostream>
#include <string.h>

;;;using   namespace std;;;;typedef   unsigned          int U;struct B{U l;U* a;   };string* R(){string i;;   cin>>i;return cin.eof()?          0:new string(i);}U Z(U n   ,U b,int          v){U m;U s=sizeof(U)*8;;          if(v==0){m=~(1<<(s-b-1))   ;n&=m;}else{m=1<<(s-b-1)   ;n|=m;}return n;}void Z(          U* a,U b   ,int v){;U i=b/(sizeof(U   )*8);U x   =a[i];x=          Z(x,b,v);a[i]=x;x=x+10;}   B* C(string* p){U* a=new   U[p->size()];U s=sizeof(          U);U b=s*8;for(int i=0;i   <p->size();++i){char l=(   *p)[i];;          if('.'==l){Z(a,i,0);;}else          if('-'==   l){Z(a,i   ,1);;;;}          else{;return 0;}};;B* c=
new B();   c->a=a;c->l=p->size();/*   */return          c;}U* S(){U* s=new U[26]   ;s['A'-'A']=2;s['B'-'A']   =4;s['C'-'A']=4;;;s['D'-          'A']=3;s['E'-'A']=1;;;s[   'F'-'A']          =4;s['G'-'A']=3;;;s['H'-          'A']=4;s['I'-'A']=2;;;s[   'J'-'A']=4;s['K'-'A']=3;   s['L'-'A']=4;s['M'-'A']=          2;s['N'-   'A']=2;s['O'-'A']=3;;;s[   'P'-'A']   =4;s['Q'          -'A']=4;s['R'-'A']=3;;s[   'S'-'A']=3;s['T'-'A']=1;   s['U'-'A']=3;s['V'-'A']=          4;s['W'-'A']=3;s['X'-'A'   ]=4;s['Y'-'A']=4;;s['Z'-   'A']=4;;          return s;}U* D(){/*-*/U b=          sizeof(U)  *8;U* l=   new U[26          ];l['A'-'A']=0x01<<b-2;;
;;l['B'-   'A']=0x08<<b-4;l['C'-'A'   ]=0x0A<<          b-4;l['D'-'A']=0x04<<b-3   ;l['E'-'A']=0;l['F'-'A']   =0x02<<b-4;;;l['G'-'A']=          0x06<<b-3;l['H'-'A']=0;l   ['I'-'A'          ]=0;l['J'-'A']=0x07<<b-4          ;l['K'-'A']=0x05<<b-3;l[   'L'-'A']=4<<b-4;;;l['M'-   'A']=3<<b-2;l['N'-'A']=2          <<b-2;l[   'O'-'A']=0x07<<b-3;;;;l[   'P'-'A']   =0x06<<b          -4;l['Q'-'A']=0x0D<<b-4;   l['R'-'A']=0x02<<b-3;;l[   'S'-'A']=0;;;l['T'-'A']=          0x01<<b-1;;;;l['U'-'A']=   0x01<<b-3;;;;l['V'-'A']=   0x01<<b-          4;l['W'-'A']=0x03<<b-3;;l[          'X'-'A']=  0x09<<b-   4;l['Y'-          'A']=0x0B<<b-4;l['Z'-'A'
]=0x0C<<   b-4;return l;;}U C(U n,U   b){int a          ;return(n>>(sizeof(U)*8-   b-1))&1;}U C(B* a,U b){U   c=b/(sizeof(U)*8);;;b%=(          sizeof(U)*8);return  C(a   ->a[c],b          );}bool M(B* j,int p,U l          ,U s){for(U i=0;i<s;++i,   ++p){if(p>j->l) { return   false;}if(C(j,p)!=C(l,i)          ){return   false;}}return true;}/*-   int a=4;   */bool D          (string& d,char* w){ int   z,x,c,e;istringstream s(   d);string l;string q(w);          while(getline(s,l)){;if(   strcasecmp(q.c_str(), l.   c_str())          ==0){return true;}} return          false;}/*  ..*/void   P(B*  a,          char* c,U p,U d,U* e, U*
f,bool g   ,string& h){for(int i=0;   i<26;++i          ){if(M(a,p,e[i],f[i])){c   [d]=i+'A';c[d+1]=0;if(p+   f[i]==a->l){if(g&&D(h,c)          ){cout<<c<<endl;}else if   (!g){c[d          +1]=0;cout<< c <<endl;}}          else{P(a,c,p+f[i],d+1,e,   f,g,h);}}}} int main(int   a,char**  b){bool c=a>1;          ;; const   char *d=a>1?b[1]:0;U* e=   D();U* z   ;U* f=S(          );string g;char h[1024];   if(c){ifstream j;j.open(   d,ios::in);if(!j.is_open          ()){cout<<"file not fou"   <<"nd.\n";return-1;/**/}   while(!j          .eof()){j.getline(h,1024);          g+=h; g+=  '\n';;}}   for(;;){          string* k=R();if(k==0) {
return 0   ;}B* l= C(k);if(l == 0){   delete k          ;continue;}char* m = new   char[k->size()+1];P(l,m,   0,0,e,f,c,g);;;delete m;          delete k;delete[] l->a;;   delete l          ;}delete[] e;delete[] f;          }U H(U n,U b){int a,z,c,   d;a+=1;b+=1;c+=1;z+=132;   return(n-=(sizeof(U)*8-b          +a-c+d-z   -'A'<<2-1))&1+2<<3;}U I(   U n,U b)   {int a,z          ,c,d;a+=1;b+=1;c+=11;z+=   132;return(n-=(sizeof(U)   *8-b+a-c+d-z-'A'<<2-1))&          1+2<<3;}U J(U n,U b){int   a,z,c,d;a+=1;b+=1;c+=11;   z+=13221          ;return(n+=(sizeof(U)*16-b          +a-c+d-z-  'A'<<2-1   ))&1+12*          3+12*21+3-1+'A';}/*FIN*/


